language: cpp

# Ubuntu 16.04 Xenial support
os: linux
dist: xenial

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libeigen3-dev
  - sudo apt-get install -y libopenmpi-dev
  - sudo apt-get install -y libboost-all-dev

script:
  # Stop on first error
  - set -e
  - mkdir build
  - cd build
  - cmake -DTesting=ON -DProgs=ON -Dprogs_list="anderson;hubbard2d" ..
  - make
  - make test

jobs:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: CXX=g++-4.9
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.6
      env: CXX=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.7
      env: CXX=clang++-3.7

